/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'message' : string,
  'timestamp' : bigint,
  'priority' : AnnouncementPriority,
}
export type AnnouncementPriority = { 'emergency' : null } |
  { 'normal' : null } |
  { 'important' : null };
export interface ContestEntry {
  'id' : bigint,
  'votes' : bigint,
  'imageUrl' : string,
  'artist' : Principal,
}
export interface PhotoPost {
  'id' : bigint,
  'author' : Principal,
  'imageUrl' : string,
  'timestamp' : bigint,
  'caption' : string,
}
export interface QuoteRequest {
  'id' : bigint,
  'to' : Principal,
  'from' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface Ticket {
  'id' : bigint,
  'status' : TicketStatus,
  'owner' : Principal,
  'event' : string,
}
export type TicketStatus = { 'active' : null } |
  { 'invalid' : null } |
  { 'used' : null } |
  { 'refunded' : null } |
  { 'validating' : null };
export interface UserProfile {
  'balance' : bigint,
  'interests' : Array<string>,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'portfolioUrl' : [] | [string],
  'empresa' : [] | [string],
  'cnpjCpf' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : bigint,
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, AnnouncementPriority],
    bigint
  >,
  'createContestEntry' : ActorMethod<[ContestEntry], undefined>,
  'createTicket' : ActorMethod<[Ticket], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContestEntries' : ActorMethod<[], Array<ContestEntry>>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getPhotoPosts' : ActorMethod<[], Array<PhotoPost>>,
  'getQuoteRequestsForUser' : ActorMethod<[], Array<QuoteRequest>>,
  'getTicket' : ActorMethod<[bigint], [] | [Ticket]>,
  'getTransactions' : ActorMethod<[Principal], Array<WalletTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTickets' : ActorMethod<[Principal], Array<Ticket>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordTransaction' : ActorMethod<[Principal, bigint, string], bigint>,
  'refundTicket' : ActorMethod<[bigint], undefined>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendQuoteRequest' : ActorMethod<[Principal, string], bigint>,
  'updateBalance' : ActorMethod<[Principal, bigint], undefined>,
  'uploadPhoto' : ActorMethod<[string, string], bigint>,
  'validateTicket' : ActorMethod<[bigint], boolean>,
  'voteContestEntry' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];