/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnouncementPriority = IDL.Variant({
  'emergency' : IDL.Null,
  'normal' : IDL.Null,
  'important' : IDL.Null,
});
export const ContestEntry = IDL.Record({
  'id' : IDL.Nat,
  'votes' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'artist' : IDL.Principal,
});
export const TicketStatus = IDL.Variant({
  'active' : IDL.Null,
  'invalid' : IDL.Null,
  'used' : IDL.Null,
  'refunded' : IDL.Null,
  'validating' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'owner' : IDL.Principal,
  'event' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'priority' : AnnouncementPriority,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Nat,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'portfolioUrl' : IDL.Opt(IDL.Text),
  'empresa' : IDL.Opt(IDL.Text),
  'cnpjCpf' : IDL.Opt(IDL.Text),
});
export const PhotoPost = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Nat,
  'caption' : IDL.Text,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, AnnouncementPriority],
      [IDL.Nat],
      [],
    ),
  'createContestEntry' : IDL.Func([ContestEntry], [], []),
  'createTicket' : IDL.Func([Ticket], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContestEntries' : IDL.Func([], [IDL.Vec(ContestEntry)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getPhotoPosts' : IDL.Func([], [IDL.Vec(PhotoPost)], ['query']),
  'getQuoteRequestsForUser' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(Ticket)], ['query']),
  'getTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func([IDL.Principal], [IDL.Vec(Ticket)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTransaction' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'refundTicket' : IDL.Func([IDL.Nat], [], []),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendQuoteRequest' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'updateBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'validateTicket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'voteContestEntry' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnouncementPriority = IDL.Variant({
    'emergency' : IDL.Null,
    'normal' : IDL.Null,
    'important' : IDL.Null,
  });
  const ContestEntry = IDL.Record({
    'id' : IDL.Nat,
    'votes' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'artist' : IDL.Principal,
  });
  const TicketStatus = IDL.Variant({
    'active' : IDL.Null,
    'invalid' : IDL.Null,
    'used' : IDL.Null,
    'refunded' : IDL.Null,
    'validating' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'owner' : IDL.Principal,
    'event' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'priority' : AnnouncementPriority,
  });
  const UserProfile = IDL.Record({
    'balance' : IDL.Nat,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'portfolioUrl' : IDL.Opt(IDL.Text),
    'empresa' : IDL.Opt(IDL.Text),
    'cnpjCpf' : IDL.Opt(IDL.Text),
  });
  const PhotoPost = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Nat,
    'caption' : IDL.Text,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, AnnouncementPriority],
        [IDL.Nat],
        [],
      ),
    'createContestEntry' : IDL.Func([ContestEntry], [], []),
    'createTicket' : IDL.Func([Ticket], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContestEntries' : IDL.Func([], [IDL.Vec(ContestEntry)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getPhotoPosts' : IDL.Func([], [IDL.Vec(PhotoPost)], ['query']),
    'getQuoteRequestsForUser' : IDL.Func(
        [],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(Ticket)], ['query']),
    'getTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func([IDL.Principal], [IDL.Vec(Ticket)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTransaction' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'refundTicket' : IDL.Func([IDL.Nat], [], []),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendQuoteRequest' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'updateBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'validateTicket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'voteContestEntry' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };